- name: Update and upgrade dnf packages
  hosts: all
  become: true
  tasks:
    - name: Update dnf cache
      dnf:
        update_cache: yes

    - name: Upgrade all dnf packages
      dnf:
        name: '*'
        state: latest
